# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\ZhangSSD\Desktop\活儿\2017-5-23-彩票预测\caop\展示.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(709, 351)
        Dialog.setSizeGripEnabled(True)
        self.n0 = QtWidgets.QTextBrowser(Dialog)
        self.n0.setGeometry(QtCore.QRect(100, 130, 51, 51))
        self.n0.setObjectName("n0")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 150, 81, 16))
        self.label.setObjectName("label")
        self.sn1 = QtWidgets.QTextBrowser(Dialog)
        self.sn1.setGeometry(QtCore.QRect(160, 10, 51, 111))
        self.sn1.setObjectName("sn1")
        self.n1 = QtWidgets.QTextBrowser(Dialog)
        self.n1.setGeometry(QtCore.QRect(160, 130, 51, 51))
        self.n1.setObjectName("n1")
        self.n2 = QtWidgets.QTextBrowser(Dialog)
        self.n2.setGeometry(QtCore.QRect(220, 130, 51, 51))
        self.n2.setObjectName("n2")
        self.n3 = QtWidgets.QTextBrowser(Dialog)
        self.n3.setGeometry(QtCore.QRect(280, 130, 51, 51))
        self.n3.setObjectName("n3")
        self.n4 = QtWidgets.QTextBrowser(Dialog)
        self.n4.setGeometry(QtCore.QRect(340, 130, 51, 51))
        self.n4.setObjectName("n4")
        self.n5 = QtWidgets.QTextBrowser(Dialog)
        self.n5.setGeometry(QtCore.QRect(400, 130, 51, 51))
        self.n5.setObjectName("n5")
        self.n6 = QtWidgets.QTextBrowser(Dialog)
        self.n6.setGeometry(QtCore.QRect(460, 130, 51, 51))
        self.n6.setObjectName("n6")
        self.n7 = QtWidgets.QTextBrowser(Dialog)
        self.n7.setGeometry(QtCore.QRect(520, 130, 51, 51))
        self.n7.setObjectName("n7")
        self.n8 = QtWidgets.QTextBrowser(Dialog)
        self.n8.setGeometry(QtCore.QRect(580, 130, 51, 51))
        self.n8.setObjectName("n8")
        self.n9 = QtWidgets.QTextBrowser(Dialog)
        self.n9.setGeometry(QtCore.QRect(640, 130, 51, 51))
        self.n9.setObjectName("n9")
        self.sn2 = QtWidgets.QTextBrowser(Dialog)
        self.sn2.setGeometry(QtCore.QRect(220, 10, 51, 111))
        self.sn2.setObjectName("sn2")
        self.sn3 = QtWidgets.QTextBrowser(Dialog)
        self.sn3.setGeometry(QtCore.QRect(280, 10, 51, 111))
        self.sn3.setObjectName("sn3")
        self.sn4 = QtWidgets.QTextBrowser(Dialog)
        self.sn4.setGeometry(QtCore.QRect(340, 10, 51, 111))
        self.sn4.setObjectName("sn4")
        self.sn5 = QtWidgets.QTextBrowser(Dialog)
        self.sn5.setGeometry(QtCore.QRect(400, 10, 51, 111))
        self.sn5.setObjectName("sn5")
        self.sn6 = QtWidgets.QTextBrowser(Dialog)
        self.sn6.setGeometry(QtCore.QRect(460, 10, 51, 111))
        self.sn6.setObjectName("sn6")
        self.sn7 = QtWidgets.QTextBrowser(Dialog)
        self.sn7.setGeometry(QtCore.QRect(520, 10, 51, 111))
        self.sn7.setObjectName("sn7")
        self.sn8 = QtWidgets.QTextBrowser(Dialog)
        self.sn8.setGeometry(QtCore.QRect(580, 10, 51, 111))
        self.sn8.setObjectName("sn8")
        self.sn9 = QtWidgets.QTextBrowser(Dialog)
        self.sn9.setGeometry(QtCore.QRect(640, 10, 51, 111))
        self.sn9.setObjectName("sn9")
        self.sn0 = QtWidgets.QTextBrowser(Dialog)
        self.sn0.setGeometry(QtCore.QRect(100, 10, 51, 111))
        self.sn0.setObjectName("sn0")
        self.xn3 = QtWidgets.QTextBrowser(Dialog)
        self.xn3.setGeometry(QtCore.QRect(280, 190, 51, 71))
        self.xn3.setObjectName("xn3")
        self.xn5 = QtWidgets.QTextBrowser(Dialog)
        self.xn5.setGeometry(QtCore.QRect(400, 190, 51, 71))
        self.xn5.setObjectName("xn5")
        self.xn6 = QtWidgets.QTextBrowser(Dialog)
        self.xn6.setGeometry(QtCore.QRect(460, 190, 51, 71))
        self.xn6.setObjectName("xn6")
        self.xn2 = QtWidgets.QTextBrowser(Dialog)
        self.xn2.setGeometry(QtCore.QRect(220, 190, 51, 71))
        self.xn2.setObjectName("xn2")
        self.xn8 = QtWidgets.QTextBrowser(Dialog)
        self.xn8.setGeometry(QtCore.QRect(580, 190, 51, 71))
        self.xn8.setObjectName("xn8")
        self.xn1 = QtWidgets.QTextBrowser(Dialog)
        self.xn1.setGeometry(QtCore.QRect(160, 190, 51, 71))
        self.xn1.setObjectName("xn1")
        self.xn7 = QtWidgets.QTextBrowser(Dialog)
        self.xn7.setGeometry(QtCore.QRect(520, 190, 51, 71))
        self.xn7.setObjectName("xn7")
        self.xn9 = QtWidgets.QTextBrowser(Dialog)
        self.xn9.setGeometry(QtCore.QRect(640, 190, 51, 71))
        self.xn9.setObjectName("xn9")
        self.xn4 = QtWidgets.QTextBrowser(Dialog)
        self.xn4.setGeometry(QtCore.QRect(340, 190, 51, 71))
        self.xn4.setObjectName("xn4")
        self.xn0 = QtWidgets.QTextBrowser(Dialog)
        self.xn0.setGeometry(QtCore.QRect(100, 190, 51, 71))
        self.xn0.setObjectName("xn0")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 81, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 230, 81, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(100, 320, 321, 16))
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(610, 320, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(10, 280, 71, 16))
        self.label_5.setObjectName("label_5")
        self.p0_1 = QtWidgets.QTextBrowser(Dialog)
        self.p0_1.setGeometry(QtCore.QRect(100, 270, 51, 31))
        self.p0_1.setObjectName("p0_1")
        self.p0_2 = QtWidgets.QTextBrowser(Dialog)
        self.p0_2.setGeometry(QtCore.QRect(160, 270, 51, 31))
        self.p0_2.setObjectName("p0_2")
        self.p0_3 = QtWidgets.QTextBrowser(Dialog)
        self.p0_3.setGeometry(QtCore.QRect(220, 270, 51, 31))
        self.p0_3.setObjectName("p0_3")
        self.p0_4 = QtWidgets.QTextBrowser(Dialog)
        self.p0_4.setGeometry(QtCore.QRect(280, 270, 51, 31))
        self.p0_4.setObjectName("p0_4")
        self.p0_5 = QtWidgets.QTextBrowser(Dialog)
        self.p0_5.setGeometry(QtCore.QRect(340, 270, 51, 31))
        self.p0_5.setObjectName("p0_5")
        self.p0_6 = QtWidgets.QTextBrowser(Dialog)
        self.p0_6.setGeometry(QtCore.QRect(400, 270, 51, 31))
        self.p0_6.setObjectName("p0_6")
        self.p0_7 = QtWidgets.QTextBrowser(Dialog)
        self.p0_7.setGeometry(QtCore.QRect(460, 270, 51, 31))
        self.p0_7.setObjectName("p0_7")
        self.p0_8 = QtWidgets.QTextBrowser(Dialog)
        self.p0_8.setGeometry(QtCore.QRect(520, 270, 51, 31))
        self.p0_8.setObjectName("p0_8")
        self.p0_9 = QtWidgets.QTextBrowser(Dialog)
        self.p0_9.setGeometry(QtCore.QRect(580, 270, 51, 31))
        self.p0_9.setObjectName("p0_9")
        self.p0_10 = QtWidgets.QTextBrowser(Dialog)
        self.p0_10.setGeometry(QtCore.QRect(640, 270, 51, 31))
        self.p0_10.setObjectName("p0_10")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "本期开奖结果"))
        self.sn0.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">3</p></body></html>"))
        self.label_2.setText(_translate("Dialog", "本期预测结果"))
        self.label_3.setText(_translate("Dialog", "下期预测结果"))
        self.label_4.setText(_translate("Dialog", "本期开奖期数：1023 2-17-05-22 12:13"))
        self.pushButton.setText(_translate("Dialog", "获取/预测"))
        self.label_5.setText(_translate("Dialog", "近40期准确率"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

