# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\PythonCode\myPthon35_Code\项目\旅游推荐\code\main.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(789, 457)
        Dialog.setSizeGripEnabled(True)
        self.textBrowser_2 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_2.setGeometry(QtCore.QRect(210, 10, 451, 31))
        self.textBrowser_2.setReadOnly(False)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 20, 181, 16))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(680, 10, 101, 31))
        self.pushButton.setObjectName("pushButton")
        self.select_time = QtWidgets.QComboBox(Dialog)
        self.select_time.setEnabled(False)
        self.select_time.setGeometry(QtCore.QRect(130, 60, 151, 31))
        self.select_time.setObjectName("select_time")
        self.select_time.addItem("")
        self.select_time.addItem("")
        self.select_time.addItem("")
        self.select_time.addItem("")
        self.select_time.addItem("")
        self.select_location = QtWidgets.QComboBox(Dialog)
        self.select_location.setEnabled(False)
        self.select_location.setGeometry(QtCore.QRect(10, 60, 111, 31))
        self.select_location.setObjectName("select_location")
        self.select_location.addItem("")
        self.select_price = QtWidgets.QComboBox(Dialog)
        self.select_price.setEnabled(False)
        self.select_price.setGeometry(QtCore.QRect(290, 60, 181, 31))
        self.select_price.setObjectName("select_price")
        self.select_price.addItem("")
        self.select_Hotel = QtWidgets.QComboBox(Dialog)
        self.select_Hotel.setEnabled(False)
        self.select_Hotel.setGeometry(QtCore.QRect(480, 60, 121, 31))
        self.select_Hotel.setObjectName("select_Hotel")
        self.select_Hotel.addItem("")
        self.select_Hotel.addItem("")
        self.select_Hotel.addItem("")
        self.select_Hotel.addItem("")
        self.select_Hotel.addItem("")
        self.select_Hotel.addItem("")
        self.select_Hotel.addItem("")
        self.select_Hotel.addItem("")
        self.select_Hotel.addItem("")
        self.select_Hotel.addItem("")
        self.select_Hotel.addItem("")
        self.select_Views = QtWidgets.QComboBox(Dialog)
        self.select_Views.setEnabled(False)
        self.select_Views.setGeometry(QtCore.QRect(610, 60, 121, 31))
        self.select_Views.setObjectName("select_Views")
        self.select_Views.addItem("")
        self.select_Views.addItem("")
        self.select_Views.addItem("")
        self.select_Views.addItem("")
        self.select_Views.addItem("")
        self.select_Views.addItem("")
        self.select_Views.addItem("")
        self.select_Views.addItem("")
        self.select_Views.addItem("")
        self.select_Views.addItem("")
        self.select_Views.addItem("")
        self.label_info = QtWidgets.QLabel(Dialog)
        self.label_info.setGeometry(QtCore.QRect(10, 430, 261, 21))
        self.label_info.setObjectName("label_info")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setEnabled(False)
        self.pushButton_2.setGeometry(QtCore.QRect(740, 60, 41, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(10, 100, 771, 321))
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.textBrowser_2.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2017-4-5</p></body></html>"))
        self.label.setText(_translate("Dialog", "输入航班日期（例：2017-05-07）"))
        self.pushButton.setText(_translate("Dialog", "获取航班信息"))
        self.select_time.setItemText(0, _translate("Dialog", "选择出发时间"))
        self.select_time.setItemText(1, _translate("Dialog", "凌晨（0:01~6:00）"))
        self.select_time.setItemText(2, _translate("Dialog", "上午（6:01~12：00）"))
        self.select_time.setItemText(3, _translate("Dialog", "下午（12:01~18:00）"))
        self.select_time.setItemText(4, _translate("Dialog", "晚上（18:01~0:00）"))
        self.select_location.setItemText(0, _translate("Dialog", "选择出发地点"))
        self.select_price.setItemText(0, _translate("Dialog", "选择价格区间"))
        self.select_Hotel.setItemText(0, _translate("Dialog", "选择酒店推荐指数"))
        self.select_Hotel.setItemText(1, _translate("Dialog", "1"))
        self.select_Hotel.setItemText(2, _translate("Dialog", "2"))
        self.select_Hotel.setItemText(3, _translate("Dialog", "3"))
        self.select_Hotel.setItemText(4, _translate("Dialog", "4"))
        self.select_Hotel.setItemText(5, _translate("Dialog", "5"))
        self.select_Hotel.setItemText(6, _translate("Dialog", "6"))
        self.select_Hotel.setItemText(7, _translate("Dialog", "7"))
        self.select_Hotel.setItemText(8, _translate("Dialog", "8"))
        self.select_Hotel.setItemText(9, _translate("Dialog", "9"))
        self.select_Hotel.setItemText(10, _translate("Dialog", "10"))
        self.select_Views.setItemText(0, _translate("Dialog", "选择景点推荐指数"))
        self.select_Views.setItemText(1, _translate("Dialog", "1"))
        self.select_Views.setItemText(2, _translate("Dialog", "2"))
        self.select_Views.setItemText(3, _translate("Dialog", "3"))
        self.select_Views.setItemText(4, _translate("Dialog", "4"))
        self.select_Views.setItemText(5, _translate("Dialog", "5"))
        self.select_Views.setItemText(6, _translate("Dialog", "6"))
        self.select_Views.setItemText(7, _translate("Dialog", "7"))
        self.select_Views.setItemText(8, _translate("Dialog", "8"))
        self.select_Views.setItemText(9, _translate("Dialog", "9"))
        self.select_Views.setItemText(10, _translate("Dialog", "10"))
        self.label_info.setText(_translate("Dialog", "基于K-means聚类算法的推荐指数生成中...."))
        self.pushButton_2.setText(_translate("Dialog", "提交"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

